<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="seema" failures="1" tests="2" name="Test" time="16.354" errors="0" timestamp="2023-03-18T17:27:34 IST">
  <testcase classname="testPackage.LoginTestclass" name="VerifyLoginFunctionalityWithIncorrectData" time="2.577"/>
  <testcase classname="testPackage.LoginTestclass" name="verifyLoginFunctionalityWithCorrectData" time="3.232">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at testPackage.LoginTestclass.verifyLoginFunctionalityWithCorrectData(LoginTestclass.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginFunctionalityWithCorrectData -->
  <testcase classname="testPackage.BaseClass" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="testPackage.BaseClass" name="@AfterTest aftertest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest aftertest -->
</testsuite> <!-- Test -->
